"""Command line entry point: registry in, manifest out.

Writes to stdout by default so the output can be piped, diffed or
redirected into a GitOps repo without the tool deciding where things
live. --out exists for the pipeline case where the path is fixed.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

from .render import build_manifest, render
from .resolve import PromotionError, resolve


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(
        prog="model-promotion-bridge",
        description="Render the VllmService manifest for whatever the registry "
                    "has promoted under an alias.",
    )
    p.add_argument("--tracking-uri", required=True,
                   help="MLflow tracking URI, e.g. sqlite:///mlflow.db or "
                        "http://mlflow:5000. Required rather than defaulted: a "
                        "silent fallback to a local store would generate a "
                        "manifest from the wrong registry and look correct.")
    p.add_argument("--model", required=True, help="registered model name")
    p.add_argument("--alias", default="production",
                   help="registry alias to resolve (default: production)")
    p.add_argument("--service-name", required=True,
                   help="metadata.name of the emitted VllmService")
    p.add_argument("--namespace", default="default")
    p.add_argument("--replicas", type=int, default=1)
    p.add_argument("--gpu", type=int, default=1)
    p.add_argument("--image", default=None,
                   help="container image; pin a digest for a reproducible "
                        "fleet. Left unset the operator applies its own "
                        "default, which is a moving tag.")
    p.add_argument("--revision-tag", default="hf_revision",
                   help="tag on the model version holding the revision")
    p.add_argument("--out", type=Path, default=None,
                   help="write here instead of stdout")
    a = p.parse_args(argv)

    try:
        promoted = resolve(a.model, a.alias, a.tracking_uri, a.revision_tag)
    except PromotionError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    manifest = build_manifest(
        promoted,
        service_name=a.service_name,
        namespace=a.namespace,
        replicas=a.replicas,
        gpu=a.gpu,
        image=a.image,
    )
    header = (
        f"generated by model-promotion-bridge from {a.model}@{a.alias} "
        f"(version {promoted.version}) — do not edit, re-run instead"
    )
    text = render(manifest, header)
    if a.out:
        a.out.parent.mkdir(parents=True, exist_ok=True)
        a.out.write_text(text)
        print(f"{a.model}@{a.alias} -> v{promoted.version} "
              f"rev {promoted.revision[:12]} -> {a.out}", file=sys.stderr)
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
